[package]
name = "fake-ioc-generator"
version = "0.1.0"
authors = ["Vladimir Luss <stainful@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
fake = "*"
md5 = "*"
sha1 = "*"
